<a href="https://colab.research.google.com/github/namoshi/chiral/blob/master/logit_chiral.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Logistic Regression for Chiral/Achiral  (Small Data Set)

In [5]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from keras.utils import np_utils

# read data from csv file
url = 'https://raw.githubusercontent.com/namoshi/chiral/master/chiral.csv'
df = pd.read_csv(url, error_bad_lines=False)

print(df.head())

data = df.values
X = data[:,:-1]
y = data[:,-1]

#print('X=', X)
#print('y=', y)

# simple logistic regression for the original data
logreg = linear_model.LogisticRegression()

logreg.fit(X, y)

pred = logreg.predict(X)

#print('pred=', pred)

score = logreg.score(X, y)

print('Logistic Regression for the original Data')
print('Recognition Rate = ', score)

coeffs = logreg.coef_
intercept = logreg.intercept_

print('Coeffs is ', coeffs)
print('Intercept is ', intercept)


# Binary representation of the variables
a_categorical = np_utils.to_categorical(X[:,0]-1)
print(a_categorical)

print(np.sum(a_categorical, axis=0))

b_categorical = np_utils.to_categorical(X[:,1]-1)

print(b_categorical)

print(np.sum(b_categorical, axis=0))

# concatenate a_categorical and b_categorical
abxy = np.c_[a_categorical, b_categorical[:,8:]]
#abxy = np.c_[np.c_[a_categorical, b_categorical[:,8:]], X[:,3]/X[:,2]]
#abxy = np.c_[np.c_[a_categorical, b_categorical[:,8:]], X[:,2:3]]

print(abxy)

print(np.sum(abxy, axis=0))

# logistic regression for categorical A and B
logreg = linear_model.LogisticRegression()

logreg.fit(abxy, y)

pred = logreg.predict(abxy)

#print('pred=', pred)

score = logreg.score(abxy, y)

print('Logistic Regression for Categorical Data')
print('Recognition Rates = ', score)

coeffs = logreg.coef_
intercept = logreg.intercept_

print('Coeffs is ', coeffs)
print('Intercept is ', intercept)



    A   Ｂ  ⅹ   ｙ  Chiral
0  14  17  2   1       1
1  14  16  1   2       1
2  16  16  7  10       1
3   6  13  1   5       1
4  13  16  1   1       1
Logistic Regression for the original Data
Recognition Rate =  0.5992779783393501
Coeffs is  [[ 0.07297842 -0.15218735 -0.0109891   0.06055069]]
Intercept is  [1.53140334]
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[10. 19.  2. 20. 24. 34. 19. 28. 22. 22. 22. 16. 19. 11.  5.  4.]
[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[ 1.  0.  0.  0.  0.  1.  1.  0.  4.  7.  2.  3. 29. 59. 51. 81. 38.]
[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[10. 19.  2. 20. 24. 34. 19. 28. 22. 22. 22. 16. 19. 11.  5.  4.  4.  7.
  